/**
 * NOCTA Gems Catalogue Data
 *
 * 宝石を追加するときは、この配列の末尾に新しいオブジェクトを追加してください（表示順=収録順）。
 *
 * title       : 和名
 * titleEn     : 英名
 * imgUrl      : 実写の直接画像URL（Wikimedia Commons / Smithsonian Open Access）
 * sourceUrl   : ライセンス確認元のファイルページURL
 * sourceName  : "Wikimedia Commons" | "Smithsonian Open Access" | "AI Generated"
 * license     : ライセンス表記（ファイルページに記載の通り）
 * credit      : クレジット表記が必要な場合の著者名。CC0で不要な場合は null
 * accentColor : 宝石本来の色（カード背景に反映。ブランド継承のハイブリッド部分）
 * hardness    : モース硬度
 * origin      : 産地
 * kotobaJa    : 石言葉（伝承ベース・表現は自作）
 * kotobaEn    : 石言葉の英語表現
 * birthMonths : 誕生石の月の配列（日本の2021年改訂リスト準拠）。非該当は []
 * descJa      : 日本語の短い鑑賞的説明文
 * descEn      : 英語の短い鑑賞的説明文（言語トグル用）
 *
 * 出典・ライセンスは全件 2026-07-04 にWebFetchで実在確認済み。
 */
const NOCTA_GEMS = [
  {
    title: "ダイヤモンド",
    titleEn: "Diamond",
    imgUrl: "https://upload.wikimedia.org/wikipedia/commons/2/2a/The_Hope_Diamond_-_SIA.jpg",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:The_Hope_Diamond_-_SIA.jpg",
    sourceName: "Wikimedia Commons",
    license: "Public Domain",
    credit: null,
    accentColor: "#6E93C4",
    hardness: "10",
    origin: "南アフリカ、ロシア、ボツワナ 他",
    kotobaJa: "永遠の絆・純潔・不屈",
    kotobaEn: "Eternal bonds, purity, invincibility",
    birthMonths: [4],
    descJa: "幾億年の圧力が研ぎ澄ませた光。写真は伝説の青、ホープダイヤモンド。",
    descEn: "Light honed by eons of pressure — pictured is the legendary blue Hope Diamond."
  },
  {
    title: "ルビー",
    titleEn: "Ruby",
    imgUrl: "https://upload.wikimedia.org/wikipedia/commons/9/93/Gemstone_Rubies.jpg",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Gemstone_Rubies.jpg",
    sourceName: "Wikimedia Commons",
    license: "CC BY-SA 4.0",
    credit: "Sasaki kijinuko",
    accentColor: "#9B111E",
    hardness: "9",
    origin: "ミャンマー、タイ、スリランカ",
    kotobaJa: "情熱・勇気・威厳",
    kotobaEn: "Passion, courage, dignity",
    birthMonths: [7],
    descJa: "血の色を宿しながら、内側では静かに光を持ち続ける石。",
    descEn: "A stone the color of blood, yet holding a quiet light within."
  },
  {
    title: "イエローサファイア",
    titleEn: "Yellow Sapphire",
    imgUrl: "https://upload.wikimedia.org/wikipedia/commons/9/90/Yellow_sapphire_oval_gemstone.JPG",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Yellow_sapphire_oval_gemstone.JPG",
    sourceName: "Wikimedia Commons",
    license: "CC BY-SA 3.0",
    credit: "Gemsphoto",
    accentColor: "#E8B923",
    hardness: "9",
    origin: "スリランカ",
    kotobaJa: "慈愛・誠実・集中",
    kotobaEn: "Benevolence, sincerity, focus",
    birthMonths: [9],
    descJa: "陽の光を溶かし込んだような、澄んだ黄の輝き。",
    descEn: "A clear yellow glow, as if sunlight had dissolved into stone."
  },
  {
    title: "エメラルド",
    titleEn: "Emerald",
    imgUrl: "https://upload.wikimedia.org/wikipedia/commons/c/ca/Chalk_emerald.jpg",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Chalk_emerald.jpg",
    sourceName: "Wikimedia Commons",
    license: "CC BY 2.0",
    credit: "Cliff (Carl Clifford)",
    accentColor: "#0F5C3D",
    hardness: "7.5-8",
    origin: "コロンビア",
    kotobaJa: "幸運・幸福・安定",
    kotobaEn: "Fortune, happiness, serenity",
    birthMonths: [5],
    descJa: "深い森の静けさを閉じ込めた、緑の結晶。",
    descEn: "A green crystal that seals in the stillness of a deep forest."
  },
  {
    title: "アメジスト",
    titleEn: "Amethyst",
    imgUrl: "https://upload.wikimedia.org/wikipedia/commons/5/5f/Amethyst_sceptre2.jpg",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Am%C3%A9thystre_sceptre2.jpg",
    sourceName: "Wikimedia Commons",
    license: "CC BY-SA 4.0",
    credit: "Didier Descouens",
    accentColor: "#9966CC",
    hardness: "7",
    origin: "ブラジル、ウルグアイ",
    kotobaJa: "誠実・心の平和",
    kotobaEn: "Sincerity and peace of mind",
    birthMonths: [2],
    descJa: "夜明け前の空の色を、結晶の中に閉じ込めた石。",
    descEn: "A stone that captures the color of the sky just before dawn."
  },
  {
    title: "オパール",
    titleEn: "Opal",
    imgUrl: "https://upload.wikimedia.org/wikipedia/commons/9/95/Precious_opal_%28Spencer_Opal_Mine%2C_Spencer%2C_Idaho%2C_USA%29_%2829284532634%29.jpg",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Precious_opal_(Spencer_Opal_Mine,_Spencer,_Idaho,_USA)_(29284532634).jpg",
    sourceName: "Wikimedia Commons",
    license: "CC BY 2.0",
    credit: "James St. John",
    accentColor: "#C9E4E0",
    hardness: "5.5-6.5",
    origin: "米国アイダホ州、スペンサー・オパール鉱山",
    kotobaJa: "希望・純真無垢",
    kotobaEn: "Hope and innocence",
    birthMonths: [10],
    descJa: "光の粒がゆらぎながら、虹をひとつずつ手放していく石。",
    descEn: "A stone where flecks of light waver, releasing rainbows one by one."
  },
  {
    title: "パライバトルマリン",
    titleEn: "Paraíba Tourmaline",
    imgUrl: "https://upload.wikimedia.org/wikipedia/commons/e/e7/Tourmaline_para%C3%AFba_%28Br%C3%A9sil%29_1.JPG",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Tourmaline_para%C3%AFba_(Br%C3%A9sil)_1.JPG",
    sourceName: "Wikimedia Commons",
    license: "CC BY-SA 3.0",
    credit: "Géry Parent",
    accentColor: "#18C2B4",
    hardness: "7-7.5",
    origin: "ブラジル、パライバ州、バタリャ鉱山",
    kotobaJa: "生命力・希望",
    kotobaEn: "Vitality and hope",
    birthMonths: [10],
    descJa: "ブラジルの大地が生んだ、電気を帯びたような青緑の光。",
    descEn: "An electric blue-green glow, born from the earth of Brazil."
  },
  {
    title: "トパーズ",
    titleEn: "Topaz",
    imgUrl: "https://upload.wikimedia.org/wikipedia/commons/0/03/Natural_blue_topaz_gemstone.jpg",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Natural_blue_topaz_gemstone.jpg",
    sourceName: "Wikimedia Commons",
    license: "CC BY-SA 4.0",
    credit: "Gemsphoto",
    accentColor: "#6BB8E0",
    hardness: "8",
    origin: "ブラジル 他",
    kotobaJa: "誠実・友情・希望",
    kotobaEn: "Honesty, friendship, hope",
    birthMonths: [11],
    descJa: "冷たい水の底を思わせる、澄んだ青の静寂。",
    descEn: "A clear blue stillness, reminiscent of the depths of cold water."
  },
  {
    title: "ガーネット",
    titleEn: "Garnet",
    imgUrl: "https://upload.wikimedia.org/wikipedia/commons/4/4f/Cut_garnet_collection.JPG",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Cut_garnet_collection.JPG",
    sourceName: "Wikimedia Commons",
    license: "CC BY 3.0",
    credit: "Humanfeather",
    accentColor: "#7B1113",
    hardness: "6.5-7.5",
    origin: "インド、アフリカ各地",
    kotobaJa: "真実・友愛・勝利",
    kotobaEn: "Truth, friendship, victory",
    birthMonths: [1],
    descJa: "燃えるような赤の奥に、静かな重さを秘めた石。",
    descEn: "A stone with a quiet weight hidden behind its burning red."
  },
  {
    title: "アクアマリン",
    titleEn: "Aquamarine",
    imgUrl: "https://upload.wikimedia.org/wikipedia/commons/6/66/Aquamarine6.jpg",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Aquamarine6.jpg",
    sourceName: "Wikimedia Commons",
    license: "CC0 1.0",
    credit: null,
    accentColor: "#9FD8DE",
    hardness: "7.5-8",
    origin: "ブラジル、ミナスジェライス州",
    kotobaJa: "沈着・勇敢・聡明",
    kotobaEn: "Composure, courage, wisdom",
    birthMonths: [3],
    descJa: "海の底の静けさを、そのまま結晶にしたような青。",
    descEn: "A blue as if the stillness of the ocean floor had crystallized."
  },
  {
    title: "タンザナイト",
    titleEn: "Tanzanite",
    imgUrl: "https://upload.wikimedia.org/wikipedia/commons/2/21/Tanzanite_%28Merelani_Tanzanite_Deposit%2C_Merelani_Hills%2C_Arusha%2C_Tanzania%29.JPG",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Tanzanite_(Merelani_Tanzanite_Deposit,_Merelani_Hills,_Arusha,_Tanzania).JPG",
    sourceName: "Wikimedia Commons",
    license: "CC BY 2.0",
    credit: "James St. John",
    accentColor: "#4B3F91",
    hardness: "6-7",
    origin: "タンザニア、アルーシャ州、メレラニ・ヒルズ",
    kotobaJa: "高貴・冷静・誇り",
    kotobaEn: "Nobility, calm, pride",
    birthMonths: [12],
    descJa: "見る角度によって色を変える、キリマンジャロ山麓の石。",
    descEn: "A stone from the foot of Kilimanjaro that shifts color with the angle of view."
  },
  {
    title: "アレキサンドライト",
    titleEn: "Alexandrite",
    imgUrl: "https://upload.wikimedia.org/wikipedia/commons/0/01/Alexandrite_26.75cts.jpg",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Alexandrite_26.75cts.jpg",
    sourceName: "Wikimedia Commons",
    license: "CC BY-SA 3.0",
    credit: "David Weinberg (Alexandrite.net)",
    accentColor: "#3F7357",
    hardness: "8.5",
    origin: "スリランカ、ブラジル",
    kotobaJa: "秘めた想い・高貴",
    kotobaEn: "Hidden feelings and nobility",
    birthMonths: [6],
    descJa: "昼と夜、ふたつの光の下で違う顔を見せる稀有な石。",
    descEn: "A rare stone that reveals two different faces under daylight and lamplight."
  },
  {
    title: "ラブラドライト",
    titleEn: "Labradorite",
    imgUrl: "https://upload.wikimedia.org/wikipedia/commons/c/c4/Labradorite_with_rare_colours.JPG",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Labradorite_with_rare_colours.JPG",
    sourceName: "Wikimedia Commons",
    license: "CC BY-SA 4.0",
    credit: "Awiejekeal",
    accentColor: "#3E7A8C",
    hardness: "6-6.5",
    origin: "マダガスカル、カナダ ラブラドール半島",
    kotobaJa: "思慕・直感・出会い",
    kotobaEn: "Longing, intuition, encounters",
    birthMonths: [],
    descJa: "石の内側に、極夜の光を隠し持つ鉱物。",
    descEn: "A mineral that hides the light of the polar night within itself."
  },
  {
    title: "ペリドット",
    titleEn: "Peridot",
    imgUrl: "https://upload.wikimedia.org/wikipedia/commons/3/3a/Peridot_with_ludwigite_inclusion_-_faceted_gemstone_peridot_from_Pakistan.jpg",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Peridot_with_ludwigite_inclusion_-_faceted_gemstone_peridot_from_Pakistan.jpg",
    sourceName: "Wikimedia Commons",
    license: "CC BY 4.0",
    credit: "Adam Stejskal / Eminerals.cz",
    accentColor: "#A6BE3F",
    hardness: "6.5-7",
    origin: "米国アリゾナ州、ミャンマー",
    kotobaJa: "夫婦の幸福・和合",
    kotobaEn: "Marital happiness and harmony",
    birthMonths: [8],
    descJa: "オリーブ色の光を、静かにたたえた火山の石。",
    descEn: "A volcanic stone that quietly holds an olive-colored light."
  },
  {
    title: "ムーンストーン",
    titleEn: "Moonstone",
    imgUrl: "https://upload.wikimedia.org/wikipedia/commons/2/25/Natural_Blue_Moonstone_loose_gemstone.jpg",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Natural_Blue_Moonstone_loose_gemstone.jpg",
    sourceName: "Wikimedia Commons",
    license: "CC BY-SA 4.0",
    credit: "Gemsphoto",
    accentColor: "#D6E4EE",
    hardness: "6-6.5",
    origin: "スリランカ、インド",
    kotobaJa: "健康・幸運・恋の予感",
    kotobaEn: "Health, fortune, a premonition of love",
    birthMonths: [6],
    descJa: "満ちる月の光を、そのまま石に閉じ込めたような輝き。",
    descEn: "A glow as if the light of a full moon had been sealed into stone."
  },
  {
    title: "ブルーサファイア",
    titleEn: "Blue Sapphire",
    imgUrl: "https://upload.wikimedia.org/wikipedia/commons/3/37/Sapphire_%28corundum%29_%2826663158752%29.jpg",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Sapphire_(corundum)_(26663158752).jpg",
    sourceName: "Wikimedia Commons",
    license: "CC BY 2.0",
    credit: "James St. John",
    accentColor: "#0F52BA",
    hardness: "9",
    origin: "ミャンマー、スリランカ、カシミール",
    kotobaJa: "慈愛・誠実・徳望",
    kotobaEn: "Benevolence, sincerity, virtue",
    birthMonths: [9],
    descJa: "王の胸元で夜空を守り続けた、深い青の静けさ。",
    descEn: "A deep blue calm that once guarded kings — a piece of the night sky."
  },
  {
    title: "パール",
    titleEn: "Pearl",
    imgUrl: "https://upload.wikimedia.org/wikipedia/commons/a/aa/Akoya_pearls.JPG",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Akoya_pearls.JPG",
    sourceName: "Wikimedia Commons",
    license: "CC BY-SA 3.0",
    credit: "Mauro Cateb",
    accentColor: "#F2ECE0",
    hardness: "2.5-4.5",
    origin: "日本（アコヤ）、オーストラリア、タヒチ",
    kotobaJa: "健康・純潔・長寿",
    kotobaEn: "Health, purity, longevity",
    birthMonths: [6],
    descJa: "海がひとしずくの月光を、長い年月をかけて包んだもの。",
    descEn: "A drop of moonlight, wrapped by the sea over long years."
  },
  {
    title: "ターコイズ",
    titleEn: "Turquoise",
    imgUrl: "https://upload.wikimedia.org/wikipedia/commons/3/3e/Turquoise_%28Ithaca_Peak_Mine%2C_near_Kingman%2C_Arizona%2C_USA%29_1.jpg",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Turquoise_(Ithaca_Peak_Mine,_near_Kingman,_Arizona,_USA)_1.jpg",
    sourceName: "Wikimedia Commons",
    license: "CC BY 2.0",
    credit: "James St. John",
    accentColor: "#3AB9C4",
    hardness: "5-6",
    origin: "イラン、米国アリゾナ州、中国",
    kotobaJa: "成功・繁栄・旅の守り",
    kotobaEn: "Success, prosperity, protection on journeys",
    birthMonths: [12],
    descJa: "乾いた大地が空の色を写しとった、旅人の石。",
    descEn: "A traveler's stone, where dry earth captured the color of the sky."
  },
  {
    title: "ラピスラズリ",
    titleEn: "Lapis Lazuli",
    imgUrl: "https://upload.wikimedia.org/wikipedia/commons/0/08/Lazurite_polie_-_94_mm_-_%28Afghanistan%29_1.JPG",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Lazurite_polie_-_94_mm_-_(Afghanistan)_1.JPG",
    sourceName: "Wikimedia Commons",
    license: "CC BY-SA 3.0",
    credit: "Parent Géry",
    accentColor: "#26619C",
    hardness: "5-6",
    origin: "アフガニスタン、チリ",
    kotobaJa: "真実・幸運・尊厳",
    kotobaEn: "Truth, fortune, dignity",
    birthMonths: [12],
    descJa: "星をちりばめた夜を、そのまま砕いて固めたような群青。",
    descEn: "An ultramarine like a starry night, crushed and made solid."
  },
  {
    title: "シトリン",
    titleEn: "Citrine",
    imgUrl: "https://upload.wikimedia.org/wikipedia/commons/6/6c/Citrine._Bahia%2C_Brazil-8845.jpg",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Citrine._Bahia,_Brazil-8845.jpg",
    sourceName: "Wikimedia Commons",
    license: "CC BY-SA 4.0",
    credit: "Raimond Spekking",
    accentColor: "#D4A017",
    hardness: "7",
    origin: "ブラジル、マダガスカル",
    kotobaJa: "繁栄・生命力・友情",
    kotobaEn: "Prosperity, vitality, friendship",
    birthMonths: [11],
    descJa: "実りの季節の光を宿した、あたたかい黄水晶。",
    descEn: "A warm quartz holding the light of the harvest season."
  },
  {
    title: "ローズクォーツ",
    titleEn: "Rose Quartz",
    imgUrl: "https://upload.wikimedia.org/wikipedia/commons/a/a7/Quartz_rose_cristallis%C3%A9_%28Br%C3%A9sil%29.jpg",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Quartz_rose_cristallis%C3%A9_(Br%C3%A9sil).jpg",
    sourceName: "Wikimedia Commons",
    license: "Public Domain",
    credit: null,
    accentColor: "#F7CAC9",
    hardness: "7",
    origin: "ブラジル、マダガスカル",
    kotobaJa: "愛・優しさ・和らぎ",
    kotobaEn: "Love, tenderness, gentleness",
    birthMonths: [],
    descJa: "淡い薔薇色の中に、静かなやさしさを湛えた石。",
    descEn: "A stone of pale rose, brimming quietly with tenderness."
  },
  {
    title: "翡翠",
    titleEn: "Jadeite",
    imgUrl: "https://upload.wikimedia.org/wikipedia/commons/e/eb/%E7%B3%B8%E9%AD%9A%E5%B7%9D%E5%B8%82%E7%94%A2%E7%BF%A1%E7%BF%A0.jpg",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:糸魚川市產翡翠.jpg",
    sourceName: "Wikimedia Commons",
    license: "CC0",
    credit: null,
    accentColor: "#4CA771",
    hardness: "6.5-7",
    origin: "ミャンマー、日本（糸魚川）、グアテマラ",
    kotobaJa: "長寿・健康・徳",
    kotobaEn: "Longevity, health, virtue",
    birthMonths: [5],
    descJa: "東洋で五つの徳を映すとされた、深くしっとりとした緑。",
    descEn: "A deep, dewy green said in the East to mirror the five virtues."
  },
  {
    title: "スピネル",
    titleEn: "Spinel",
    imgUrl: "https://upload.wikimedia.org/wikipedia/commons/c/cb/Spinel_%28Mogok_Metamorphic_Belt%2C_Jurassic_to_Miocene%3B_Momeik_Township%2C_Shan_State%2C_Burma%29.jpg",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Spinel_(Mogok_Metamorphic_Belt,_Jurassic_to_Miocene;_Momeik_Township,_Shan_State,_Burma).jpg",
    sourceName: "Wikimedia Commons",
    license: "CC BY 2.0",
    credit: "James St. John",
    accentColor: "#CB2A4E",
    hardness: "7.5-8",
    origin: "ミャンマー（モゴック）、タンザニア、スリランカ",
    kotobaJa: "内面の充実・安全",
    kotobaEn: "Inner fulfillment and safety",
    birthMonths: [8],
    descJa: "長くルビーと呼ばれてきた、燃える色の知られざる主役。",
    descEn: "Long mistaken for ruby — an unsung protagonist in burning color."
  },
  {
    title: "モルガナイト",
    titleEn: "Morganite",
    imgUrl: "https://upload.wikimedia.org/wikipedia/commons/c/c8/Berillo_variante_morganite%2C_da_galilea%2C_urucum%2C_minas_geiras%2C_brasile.JPG",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Berillo_variante_morganite,_da_galilea,_urucum,_minas_geiras,_brasile.JPG",
    sourceName: "Wikimedia Commons",
    license: "CC BY 3.0",
    credit: "Sailko",
    accentColor: "#EAB0AA",
    hardness: "7.5-8",
    origin: "ブラジル（ミナスジェライス）、マダガスカル",
    kotobaJa: "愛らしさ・優美・清純",
    kotobaEn: "Charm, elegance, innocence",
    birthMonths: [4],
    descJa: "夜明けの桜色を閉じ込めた、やわらかな光の石。",
    descEn: "A soft-lit stone that holds the cherry color of dawn."
  },
  {
    title: "クンツァイト",
    titleEn: "Kunzite",
    imgUrl: "https://upload.wikimedia.org/wikipedia/commons/7/7a/Kunzite_%28Afghanistan%29.jpg",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Kunzite_(Afghanistan).jpg",
    sourceName: "Wikimedia Commons",
    license: "Public Domain",
    credit: null,
    accentColor: "#D69AC4",
    hardness: "6.5-7",
    origin: "アフガニスタン、パキスタン、ブラジル",
    kotobaJa: "無限の愛・純粋",
    kotobaEn: "Infinite love and purity",
    birthMonths: [9],
    descJa: "夕暮れの薄紫が、静かに結晶になった石。",
    descEn: "The pale violet of dusk, quietly crystallized."
  },
  {
    title: "ロードクロサイト",
    titleEn: "Rhodochrosite",
    imgUrl: "https://upload.wikimedia.org/wikipedia/commons/a/ae/Alma_King_rhodochrosite.jpg",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Alma_King_rhodochrosite.jpg",
    sourceName: "Wikimedia Commons",
    license: "CC BY-SA 3.0",
    credit: "Kimon Berlin",
    accentColor: "#C0395B",
    hardness: "3.5-4",
    origin: "アルゼンチン、米国コロラド州、ペルー",
    kotobaJa: "新しい愛・清浄",
    kotobaEn: "New love and clarity",
    birthMonths: [],
    descJa: "アンデスの薔薇と呼ばれる、縞をまとった深紅。",
    descEn: "Crimson wrapped in bands — the rose of the Andes."
  },
  {
    title: "マラカイト",
    titleEn: "Malachite",
    imgUrl: "https://upload.wikimedia.org/wikipedia/commons/c/c6/Botryoidal_malachite_01.jpg",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Botryoidal_malachite_01.jpg",
    sourceName: "Wikimedia Commons",
    license: "CC BY-SA 4.0",
    credit: "M. Schaap",
    accentColor: "#1E6B4F",
    hardness: "3.5-4",
    origin: "コンゴ民主共和国、ザンビア、ロシア（ウラル）",
    kotobaJa: "守護・再生",
    kotobaEn: "Protection and rebirth",
    birthMonths: [],
    descJa: "孔雀の羽のような縞が、渦を巻いて眠る緑の石。",
    descEn: "A green stone where peacock-feather bands sleep in swirls."
  },
  {
    title: "アンモライト",
    titleEn: "Ammolite",
    imgUrl: "https://upload.wikimedia.org/wikipedia/commons/d/da/BLW_Ammolite_ammonite.jpg",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:BLW_Ammolite_ammonite.jpg",
    sourceName: "Wikimedia Commons",
    license: "CC BY-SA 2.0 UK",
    credit: "Mike Peel",
    accentColor: "#C24E2C",
    hardness: "3.5-4.5",
    origin: "カナダ、アルバータ州（唯一の商業産地）",
    kotobaJa: "変化・時の記憶",
    kotobaEn: "Transformation and the memory of time",
    birthMonths: [],
    descJa: "七千万年の眠りが、虹色の光になった化石。",
    descEn: "A fossil whose seventy-million-year sleep became iridescent light."
  },
  {
    title: "フローライト",
    titleEn: "Fluorite",
    imgUrl: "https://upload.wikimedia.org/wikipedia/commons/e/ef/Fluorine_MHNT.MIN.2010.16.1.jpg",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Fluorine_MHNT.MIN.2010.16.1.jpg",
    sourceName: "Wikimedia Commons",
    license: "CC BY-SA 3.0",
    credit: "Didier Descouens",
    accentColor: "#3E7CC4",
    hardness: "4",
    origin: "中国、メキシコ、英国、フランス",
    kotobaJa: "秘められた美徳・天才",
    kotobaEn: "Hidden virtue and genius",
    birthMonths: [],
    descJa: "光の下で色を重ねる、氷のように透きとおる結晶。",
    descEn: "An ice-clear crystal that layers colors under the light."
  },
  {
    title: "ウォーターメロントルマリン",
    titleEn: "Watermelon Tourmaline",
    imgUrl: "https://upload.wikimedia.org/wikipedia/commons/c/c4/Rough_%28bi-color%29_Watermelon_Tourmaline.jpg",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Rough_(bi-color)_Watermelon_Tourmaline.jpg",
    sourceName: "Wikimedia Commons",
    license: "CC BY-SA 4.0",
    credit: "Paweł Maliszczak",
    accentColor: "#E84D8A",
    hardness: "7-7.5",
    origin: "ブラジル、ミナスジェライス州 他",
    kotobaJa: "調和・寛大",
    kotobaEn: "Harmony and generosity",
    birthMonths: [10],
    descJa: "果実のように、紅と緑をひとつの結晶に宿す石。",
    descEn: "A stone that holds red and green in one crystal, like fruit."
  },
  {
    title: "サンストーン",
    titleEn: "Sunstone",
    imgUrl: "https://upload.wikimedia.org/wikipedia/commons/0/0e/Sunstone_%28Tertiary%3B_Spectrum_Mine%2C_Oregon%2C_USA%29_1.jpg",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Sunstone_(Tertiary;_Spectrum_Mine,_Oregon,_USA)_1.jpg",
    sourceName: "Wikimedia Commons",
    license: "CC BY 2.0",
    credit: "James St. John",
    accentColor: "#E17A47",
    hardness: "6-6.5",
    origin: "米国オレゴン州、インド、ノルウェー",
    kotobaJa: "輝き・自由・幸福",
    kotobaEn: "Radiance, freedom, happiness",
    birthMonths: [],
    descJa: "石の中に朝日の粒が舞う、光のかけら。",
    descEn: "A fragment of light, where grains of sunrise dance within stone."
  },
  {
    title: "アイオライト",
    titleEn: "Iolite",
    imgUrl: "https://upload.wikimedia.org/wikipedia/commons/2/27/Cordi%C3%A9rite_var._iolite_1.jpg",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Cordiérite_var._iolite_1.jpg",
    sourceName: "Wikimedia Commons",
    license: "CC BY-SA 3.0",
    credit: "Géry Parent",
    accentColor: "#4E5EA8",
    hardness: "7-7.5",
    origin: "マダガスカル、インド、スリランカ",
    kotobaJa: "誠実・貞節・道を示す",
    kotobaEn: "Sincerity, fidelity, guidance",
    birthMonths: [3],
    descJa: "航海者の羅針盤となった、菫色の静かな石。",
    descEn: "A quiet violet stone that once served sailors as a compass."
  },
  {
    title: "ラリマー",
    titleEn: "Larimar",
    imgUrl: "https://upload.wikimedia.org/wikipedia/commons/4/4b/Larimar.jpg",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Larimar.jpg",
    sourceName: "Wikimedia Commons",
    license: "Public Domain",
    credit: null,
    accentColor: "#4CB8C9",
    hardness: "4.5-5",
    origin: "ドミニカ共和国、バラオナ（世界唯一の産地）",
    kotobaJa: "愛と平和・癒し",
    kotobaEn: "Love, peace, healing",
    birthMonths: [],
    descJa: "カリブの浅瀬の光を、そのまま閉じ込めた石。",
    descEn: "A stone that seals in the light of Caribbean shallows."
  },
  {
    title: "琥珀",
    titleEn: "Amber",
    imgUrl: "https://upload.wikimedia.org/wikipedia/commons/8/88/Baltic_amber_Coleoptera_Melandryidae.JPG",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Baltic_amber_Coleoptera_Melandryidae.JPG",
    sourceName: "Wikimedia Commons",
    license: "CC BY-SA 3.0",
    credit: "Anders L. Damgaard",
    accentColor: "#CF8722",
    hardness: "2-2.5",
    origin: "バルト海沿岸（ポーランド、リトアニア 他）",
    kotobaJa: "抱擁・時の記憶",
    kotobaEn: "Embrace and the memory of time",
    birthMonths: [],
    descJa: "太古の森の涙が、金色の時間になった宝石。小さな旅人を抱いたまま。",
    descEn: "Tears of an ancient forest turned to golden time — still holding a tiny traveler."
  },
  {
    title: "ベニトアイト",
    titleEn: "Benitoite",
    imgUrl: "https://upload.wikimedia.org/wikipedia/commons/6/6b/Benitoite_HD.jpg",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Benitoite_HD.jpg",
    sourceName: "Wikimedia Commons",
    license: "CC BY-SA 4.0",
    credit: "Didier Descouens",
    accentColor: "#2E5FB0",
    hardness: "6-6.5",
    origin: "米国カリフォルニア州サンベニート郡（事実上唯一の産地）",
    kotobaJa: "静かな情熱",
    kotobaEn: "Quiet passion",
    birthMonths: [],
    descJa: "たったひとつの谷でしか見つからない、青い星のかけら。",
    descEn: "A shard of blue star found in only one valley on earth."
  },
  {
    title: "オブシディアン",
    titleEn: "Obsidian",
    imgUrl: "https://upload.wikimedia.org/wikipedia/commons/d/d3/Snowflake_obsidian_1.jpg",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Snowflake_obsidian_1.jpg",
    sourceName: "Wikimedia Commons",
    license: "CC BY 2.0",
    credit: "James St. John",
    accentColor: "#4A4A52",
    hardness: "5-5.5",
    origin: "米国、メキシコ、日本などの火山地帯",
    kotobaJa: "内省・守護",
    kotobaEn: "Introspection and protection",
    birthMonths: [],
    descJa: "火山の夜に降る雪を、そのまま封じた黒いガラス。",
    descEn: "Black glass that sealed in snow falling on a volcanic night."
  }
];
