/**
 * NOCTA Flora Catalogue Data
 *
 * 花を追加するときは、この配列の適切な位置に新しいオブジェクトを追加してください（表示順=収録順・おおむね季節順）。
 *
 * title       : 和名
 * titleEn     : 英名
 * sci         : 学名
 * imgUrl      : 実写の直接画像URL（Wikimedia Commons）
 * sourceUrl   : ライセンス確認元のファイルページURL
 * sourceName  : "Wikimedia Commons"
 * license     : ライセンス表記（ファイルページに記載の通り）
 * credit      : クレジット表記が必要な場合の著者名。CC0/PDで不要な場合は null
 * accentColor : 花の代表色（カード背景に反映）
 * season      : 開花期
 * origin      : 原産・分布
 * hanakotobaJa: 花言葉（伝承ベース・表現は自作）
 * hanakotobaEn: 花言葉の英語表現
 * birthMonths : 誕生月の花の配列（代表的な月）。非該当は []
 * descJa      : 日本語の短い鑑賞的説明文
 * descEn      : 英語の短い鑑賞的説明文（言語トグル用）
 *
 * 出典・ライセンスは全件 2026-07-04 にWebFetchで実在確認済み。
 */
const NOCTA_FLORA = [
  {
    title: "桜",
    titleEn: "Cherry Blossom",
    sci: "Prunus × yedoensis",
    imgUrl: "https://upload.wikimedia.org/wikipedia/commons/0/0f/Cherry_blossoms_%28Prunus_x_yedoensis_%27Awanui%27%29_with_dew_drops_close-up.jpg",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Cherry_blossoms_(Prunus_x_yedoensis_'Awanui')_with_dew_drops_close-up.jpg",
    sourceName: "Wikimedia Commons",
    license: "Public Domain",
    credit: null,
    accentColor: "#F7C6D4",
    hanaForm: "sakura",
    season: "3月〜4月",
    origin: "日本",
    hanakotobaJa: "精神の美・優美な女性",
    hanakotobaEn: "Beauty of spirit, a graceful woman",
    birthMonths: [4],
    descJa: "満開の一瞬のために、一年を待つ花。",
    descEn: "A flower that waits a year for one moment in full bloom."
  },
  {
    title: "梅",
    titleEn: "Plum Blossom",
    sci: "Prunus mume",
    imgUrl: "https://upload.wikimedia.org/wikipedia/commons/5/5a/Prunus_mume_G02.JPG",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Prunus_mume_G02.JPG",
    sourceName: "Wikimedia Commons",
    license: "CC BY-SA 3.0",
    credit: "Hide-sp",
    accentColor: "#D96BA0",
    hanaForm: "komori",
    season: "2月〜3月",
    origin: "中国原産、日本・東アジア",
    hanakotobaJa: "忍耐・高潔・忠実",
    hanakotobaEn: "Patience, nobility, fidelity",
    birthMonths: [2],
    descJa: "まだ雪の残る枝で、春をいちばんに告げる花。",
    descEn: "On branches still holding snow, the first to announce spring."
  },
  {
    title: "椿",
    titleEn: "Camellia",
    sci: "Camellia japonica",
    imgUrl: "https://upload.wikimedia.org/wikipedia/commons/e/e9/Camellia_japonica_NBG.jpg",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Camellia_japonica_NBG.jpg",
    sourceName: "Wikimedia Commons",
    license: "CC BY-SA 3.0",
    credit: "PumpkinSky",
    accentColor: "#D64A6E",
    hanaForm: "layered",
    season: "12月〜4月",
    origin: "日本、東アジア",
    hanakotobaJa: "控えめな素晴らしさ・気取らない優美",
    hanakotobaEn: "Modest splendor, unpretentious grace",
    birthMonths: [2],
    descJa: "冬の庭で、静かに紅をともす花。",
    descEn: "A flower that quietly lights crimson in the winter garden."
  },
  {
    title: "チューリップ",
    titleEn: "Tulip",
    sci: "Tulipa gesneriana",
    imgUrl: "https://upload.wikimedia.org/wikipedia/commons/4/4c/Tulip_cv._34.JPG",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Tulip_cv._34.JPG",
    sourceName: "Wikimedia Commons",
    license: "CC BY-SA 3.0",
    credit: "Andrey Korzun",
    accentColor: "#E63A2E",
    hanaForm: "tulip",
    season: "3月〜5月",
    origin: "中央アジア、トルコ",
    hanakotobaJa: "思いやり・博愛",
    hanakotobaEn: "Compassion and charity",
    birthMonths: [3],
    descJa: "春の光をそのまま器にしたような花。",
    descEn: "A flower like a vessel holding the light of spring."
  },
  {
    title: "すずらん",
    titleEn: "Lily of the Valley",
    sci: "Convallaria majalis",
    imgUrl: "https://upload.wikimedia.org/wikipedia/commons/6/66/European_Lily_of_the_Valley_%28Convallaria_majalis%29_-_Oslo%2C_Norway_2020-08-30.jpg",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:European_Lily_of_the_Valley_(Convallaria_majalis)_-_Oslo,_Norway_2020-08-30.jpg",
    sourceName: "Wikimedia Commons",
    license: "CC BY-SA 4.0",
    credit: "Ryan Hodnett",
    accentColor: "#EAF0E6",
    hanaForm: "bell",
    season: "4月〜5月",
    origin: "ヨーロッパ、日本（北海道など）",
    hanakotobaJa: "再び幸せが訪れる・純粋",
    hanakotobaEn: "Return of happiness, purity",
    birthMonths: [5],
    descJa: "森の足もとで、小さな鈴を鳴らすように咲く花。",
    descEn: "Blooming at the forest's feet like tiny ringing bells."
  },
  {
    title: "藤",
    titleEn: "Wisteria",
    sci: "Wisteria floribunda",
    imgUrl: "https://upload.wikimedia.org/wikipedia/commons/6/69/Japanese_wisteria%2C_Ashikaga_Flower_Park_2.jpg",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Japanese_wisteria,_Ashikaga_Flower_Park_2.jpg",
    sourceName: "Wikimedia Commons",
    license: "CC BY-SA 4.0",
    credit: "SLIMHANNYA",
    accentColor: "#8172B8",
    hanaForm: "bell",
    season: "4月〜5月",
    origin: "日本",
    hanakotobaJa: "優しさ・歓迎・決して離れない",
    hanakotobaEn: "Kindness, welcome, steadfast love",
    birthMonths: [5],
    descJa: "薄紫の雨のように、風に揺れて垂れる花。",
    descEn: "Hanging like pale purple rain, swaying in the wind."
  },
  {
    title: "牡丹",
    titleEn: "Tree Peony",
    sci: "Paeonia suffruticosa",
    imgUrl: "https://upload.wikimedia.org/wikipedia/commons/5/59/Paeonia_suffruticosa_Fuso-no-Tsukasa_JdP_2013-04-28_n01.jpg",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Paeonia_suffruticosa_Fuso-no-Tsukasa_JdP_2013-04-28_n01.jpg",
    sourceName: "Wikimedia Commons",
    license: "CC BY 2.5",
    credit: "Marie-Lan Nguyen",
    accentColor: "#C85C8E",
    hanaForm: "layered",
    season: "4月〜5月",
    origin: "中国",
    hanakotobaJa: "風格・富貴",
    hanakotobaEn: "Dignity and prosperity",
    birthMonths: [5],
    descJa: "ひらくたびに、あたりの空気を変える大輪の花。",
    descEn: "A great bloom that changes the air each time it opens."
  },
  {
    title: "芍薬",
    titleEn: "Chinese Peony",
    sci: "Paeonia lactiflora",
    imgUrl: "https://upload.wikimedia.org/wikipedia/commons/8/83/Paeonia_lactiflora_Philomele_2015_02.jpg",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Paeonia_lactiflora_Philomele_2015_02.jpg",
    sourceName: "Wikimedia Commons",
    license: "CC BY-SA 4.0",
    credit: "Agnieszka Kwiecień, Nova",
    accentColor: "#E38AA8",
    hanaForm: "layered",
    season: "5月〜6月",
    origin: "中国北部〜シベリア東部",
    hanakotobaJa: "はにかみ・慎ましさ",
    hanakotobaEn: "Bashfulness and modesty",
    birthMonths: [6],
    descJa: "立てば芍薬と歌われた、初夏のやわらかな大輪。",
    descEn: "The soft grand bloom of early summer, praised in old verse."
  },
  {
    title: "バラ",
    titleEn: "Rose",
    sci: "Rosa 'Double Delight'",
    imgUrl: "https://upload.wikimedia.org/wikipedia/commons/3/38/A_rose.JPG",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:A_rose.JPG",
    sourceName: "Wikimedia Commons",
    license: "CC BY-SA 4.0",
    credit: "Mrmariokartguy",
    accentColor: "#C41E3A",
    hanaForm: "layered",
    season: "5月〜11月",
    origin: "北半球の温帯（園芸種は世界各地）",
    hanakotobaJa: "愛・美",
    hanakotobaEn: "Love and beauty",
    birthMonths: [6],
    descJa: "幾重にも重なる花びらに、物語を隠す花。",
    descEn: "A flower hiding stories within its layered petals."
  },
  {
    title: "紫陽花",
    titleEn: "Hydrangea",
    sci: "Hydrangea macrophylla",
    imgUrl: "https://upload.wikimedia.org/wikipedia/commons/1/14/Hydrangea_macrophylla_2021.2.jpg",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Hydrangea_macrophylla_2021.2.jpg",
    sourceName: "Wikimedia Commons",
    license: "CC BY-SA 4.0",
    credit: "Syariful Msth",
    accentColor: "#5F82BD",
    hanaForm: "komori",
    season: "6月〜7月",
    origin: "日本",
    hanakotobaJa: "辛抱強い愛情・家族団欒",
    hanakotobaEn: "Patient love, family bonds",
    birthMonths: [6],
    descJa: "雨の季節に、七つの色を渡り歩く花。",
    descEn: "A flower that wanders through seven colors in the rainy season."
  },
  {
    title: "花菖蒲",
    titleEn: "Japanese Iris",
    sci: "Iris ensata",
    imgUrl: "https://upload.wikimedia.org/wikipedia/commons/5/5a/Iris_ensata_%28Iridaceae%29_%2849869833552%29.jpg",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Iris_ensata_(Iridaceae)_(49869833552).jpg",
    sourceName: "Wikimedia Commons",
    license: "CC BY-SA 2.0",
    credit: "Dr. Alexey Yakovlev",
    accentColor: "#6A4C9C",
    hanaForm: "star",
    season: "6月〜7月",
    origin: "日本、東アジア",
    hanakotobaJa: "優しい心・嬉しい知らせ",
    hanakotobaEn: "A gentle heart, good news",
    birthMonths: [6],
    descJa: "水辺に立ち、雨の晴れ間を待つ花。",
    descEn: "Standing at the water's edge, awaiting a break in the rain."
  },
  {
    title: "ラベンダー",
    titleEn: "Lavender",
    sci: "Lavandula angustifolia",
    imgUrl: "https://upload.wikimedia.org/wikipedia/commons/2/2e/Lavandula_angustifolia_002.JPG",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Lavandula_angustifolia_002.JPG",
    sourceName: "Wikimedia Commons",
    license: "CC BY-SA 3.0",
    credit: "H. Zell",
    accentColor: "#9B87C4",
    hanaForm: "komori",
    season: "6月〜7月",
    origin: "地中海沿岸",
    hanakotobaJa: "沈黙・期待・あなたを待っています",
    hanakotobaEn: "Silence, expectation, waiting for you",
    birthMonths: [7],
    descJa: "紫の畝が、風の音まで香りに変える花。",
    descEn: "Purple rows that turn even the sound of wind into fragrance."
  },
  {
    title: "蓮",
    titleEn: "Lotus",
    sci: "Nelumbo nucifera",
    imgUrl: "https://upload.wikimedia.org/wikipedia/commons/e/ed/Sacred_lotus_Nelumbo_nucifera.jpg",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Sacred_lotus_Nelumbo_nucifera.jpg",
    sourceName: "Wikimedia Commons",
    license: "CC BY-SA 3.0",
    credit: "T. Voekler",
    accentColor: "#E8A0BF",
    hanaForm: "layered",
    season: "7月〜8月",
    origin: "アジア（インド原産）",
    hanakotobaJa: "清らかな心・神聖",
    hanakotobaEn: "A pure heart, holiness",
    birthMonths: [7],
    descJa: "泥の中から、夜明けとともにひらく花。",
    descEn: "Rising from the mud, it opens with the dawn."
  },
  {
    title: "ユリ（カサブランカ）",
    titleEn: "Casa Blanca Lily",
    sci: "Lilium 'Casa Blanca'",
    imgUrl: "https://upload.wikimedia.org/wikipedia/commons/c/ca/Casa_Blanca_lily_01.jpg",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Casa_Blanca_lily_01.jpg",
    sourceName: "Wikimedia Commons",
    license: "CC BY-SA 3.0",
    credit: "Joe Mabel",
    accentColor: "#EDE6D6",
    hanaForm: "bell",
    season: "6月〜8月",
    origin: "園芸品種（日本のヤマユリ等が交配親）",
    hanakotobaJa: "威厳・純潔・高貴",
    hanakotobaEn: "Majesty, purity, nobility",
    birthMonths: [7],
    descJa: "白い大輪が、夏の夕暮れに香りを放つ花。",
    descEn: "Great white blooms releasing fragrance into the summer dusk."
  },
  {
    title: "ひまわり",
    titleEn: "Sunflower",
    sci: "Helianthus annuus",
    imgUrl: "https://upload.wikimedia.org/wikipedia/commons/e/eb/Sunflowers_helianthus_annuus.jpg",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Sunflowers_helianthus_annuus.jpg",
    sourceName: "Wikimedia Commons",
    license: "Public Domain",
    credit: null,
    accentColor: "#F5C518",
    hanaForm: "kiku",
    season: "7月〜9月",
    origin: "北アメリカ",
    hanakotobaJa: "あなただけを見つめる・憧れ",
    hanakotobaEn: "Eyes only for you, adoration",
    birthMonths: [8],
    descJa: "夏の太陽を、まっすぐに見上げ続ける花。",
    descEn: "A flower that keeps looking straight up at the summer sun."
  },
  {
    title: "朝顔",
    titleEn: "Morning Glory",
    sci: "Ipomoea nil",
    imgUrl: "https://upload.wikimedia.org/wikipedia/commons/c/cd/Flower_of_Ipomoea_nil_20180624.jpg",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Flower_of_Ipomoea_nil_20180624.jpg",
    sourceName: "Wikimedia Commons",
    license: "CC BY-SA 4.0",
    credit: "そらみみ",
    accentColor: "#4A6FB5",
    hanaForm: "komori",
    season: "7月〜9月",
    origin: "熱帯アメリカ原産、日本で園芸文化として発展",
    hanakotobaJa: "はかない恋・固い絆",
    hanakotobaEn: "Fleeting love, strong bonds",
    birthMonths: [8],
    descJa: "夜明けのわずかな時間だけ、青をひらく花。",
    descEn: "Opening its blue for only the brief hours of dawn."
  },
  {
    title: "桔梗",
    titleEn: "Balloon Flower",
    sci: "Platycodon grandiflorus",
    imgUrl: "https://upload.wikimedia.org/wikipedia/commons/6/6a/Platycodon_grandiflorus_%28flower_s2%29.jpg",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Platycodon_grandiflorus_(flower_s2).jpg",
    sourceName: "Wikimedia Commons",
    license: "CC BY-SA 4.0",
    credit: "Alpsdake",
    accentColor: "#5B6FB0",
    hanaForm: "star",
    season: "6月〜9月",
    origin: "日本、東アジア（秋の七草）",
    hanakotobaJa: "永遠の愛・気品・誠実",
    hanakotobaEn: "Eternal love, grace, sincerity",
    birthMonths: [9],
    descJa: "秋風の中で、星のかたちに咲く花。",
    descEn: "Blooming in the shape of a star in the autumn wind."
  },
  {
    title: "彼岸花",
    titleEn: "Red Spider Lily",
    sci: "Lycoris radiata",
    imgUrl: "https://upload.wikimedia.org/wikipedia/commons/4/48/Red_Spider_Lily----Lycoris_radiata.jpg",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Red_Spider_Lily----Lycoris_radiata.jpg",
    sourceName: "Wikimedia Commons",
    license: "CC BY-SA 4.0",
    credit: "Jim Evans",
    accentColor: "#C41E3A",
    hanaForm: "kiku",
    season: "9月（秋の彼岸頃）",
    origin: "中国原産、日本全国に帰化",
    hanakotobaJa: "情熱・再会",
    hanakotobaEn: "Passion and reunion",
    birthMonths: [9],
    descJa: "秋の彼岸に、炎のような紅を掲げる花。",
    descEn: "Raising flame-like crimson at the autumn equinox."
  },
  {
    title: "コスモス",
    titleEn: "Cosmos",
    sci: "Cosmos bipinnatus",
    imgUrl: "https://upload.wikimedia.org/wikipedia/commons/b/b9/Cosmea_%28Cosmos_bipinnatus%29_01.JPG",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Cosmea_(Cosmos_bipinnatus)_01.JPG",
    sourceName: "Wikimedia Commons",
    license: "CC BY-SA 4.0",
    credit: "Dominicus Johannes Bergsma",
    accentColor: "#E68FB0",
    hanaForm: "sakura",
    season: "9月〜10月",
    origin: "メキシコ",
    hanakotobaJa: "乙女の真心・調和",
    hanakotobaEn: "A maiden's sincerity, harmony",
    birthMonths: [10],
    descJa: "秋の高い空に向かって、風とともに揺れる花。",
    descEn: "Swaying with the wind toward the high autumn sky."
  },
  {
    title: "金木犀",
    titleEn: "Fragrant Olive",
    sci: "Osmanthus fragrans var. aurantiacus",
    imgUrl: "https://upload.wikimedia.org/wikipedia/commons/2/27/Osmanthus_fragrans_var._aurantiacus.JPG",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Osmanthus_fragrans_var._aurantiacus.JPG",
    sourceName: "Wikimedia Commons",
    license: "CC BY-SA 3.0",
    credit: "Qwert1234",
    accentColor: "#F08A24",
    hanaForm: "komori",
    season: "9月〜10月",
    origin: "中国原産、日本には江戸時代に渡来",
    hanakotobaJa: "謙虚・気高い人・初恋",
    hanakotobaEn: "Modesty, nobility, first love",
    birthMonths: [10],
    descJa: "姿より先に、香りで秋を知らせる花。",
    descEn: "A flower that announces autumn by fragrance before form."
  },
  {
    title: "菊",
    titleEn: "Chrysanthemum",
    sci: "Chrysanthemum × morifolium",
    imgUrl: "https://upload.wikimedia.org/wikipedia/commons/5/51/Chrysanthemum_%C3%97_morifolium_Dompierre_1.jpg",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Chrysanthemum_%C3%97_morifolium_Dompierre_1.jpg",
    sourceName: "Wikimedia Commons",
    license: "CC0 1.0",
    credit: null,
    accentColor: "#D4A02C",
    hanaForm: "kiku",
    season: "10月〜11月",
    origin: "中国原産、日本で独自に発展",
    hanakotobaJa: "高貴・高潔・高尚",
    hanakotobaEn: "Nobility, integrity, refinement",
    birthMonths: [11],
    descJa: "霜の季節まで、凛と咲き続ける花。",
    descEn: "Blooming with dignity until the season of frost."
  },
  {
    title: "山茶花",
    titleEn: "Sasanqua",
    sci: "Camellia sasanqua",
    imgUrl: "https://upload.wikimedia.org/wikipedia/commons/0/08/Camellia_sasanqua1065947%E3%82%B5%E3%82%B6%E3%83%B3%E3%82%AB%2C%E5%B1%B1%E8%8C%B6%E8%8A%B1.JPG",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Camellia_sasanqua1065947サザンカ,山茶花.JPG",
    sourceName: "Wikimedia Commons",
    license: "CC BY-SA 3.0",
    credit: "松岡明芳",
    accentColor: "#D96A8B",
    hanaForm: "layered",
    season: "10月〜12月",
    origin: "日本固有種",
    hanakotobaJa: "困難に打ち勝つ・ひたむきさ",
    hanakotobaEn: "Overcoming hardship, devotion",
    birthMonths: [11],
    descJa: "冬のはじまりに、垣根を紅く染める花。",
    descEn: "Dyeing the hedges crimson at winter's start."
  },
  {
    title: "シクラメン",
    titleEn: "Cyclamen",
    sci: "Cyclamen persicum",
    imgUrl: "https://upload.wikimedia.org/wikipedia/commons/3/31/Cyclamen_persicum_flower2.JPG",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Cyclamen_persicum_flower2.JPG",
    sourceName: "Wikimedia Commons",
    license: "CC BY-SA 4.0",
    credit: "Leonardo Ré-Jorge",
    accentColor: "#C6407A",
    hanaForm: "bell",
    season: "11月〜3月",
    origin: "地中海東部",
    hanakotobaJa: "遠慮・内気なはにかみ",
    hanakotobaEn: "Reserve and shy bashfulness",
    birthMonths: [12],
    descJa: "冬の窓辺で、炎を逆さに灯すような花。",
    descEn: "Like an upside-down flame lit at the winter window."
  },
  {
    title: "水仙",
    titleEn: "Narcissus",
    sci: "Narcissus poeticus",
    imgUrl: "https://upload.wikimedia.org/wikipedia/commons/7/79/Narcissus_poeticus_Spechtensee_01.JPG",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Narcissus_poeticus_Spechtensee_01.JPG",
    sourceName: "Wikimedia Commons",
    license: "CC BY-SA 4.0",
    credit: "Uoaei1",
    accentColor: "#F2C14E",
    hanaForm: "star",
    season: "12月〜4月",
    origin: "地中海沿岸",
    hanakotobaJa: "自己愛・神秘",
    hanakotobaEn: "Self-love and mystery",
    birthMonths: [1],
    descJa: "雪の中で、春の香りをひとりで抱く花。",
    descEn: "Holding the scent of spring alone in the snow."
  }
];
