export const CRESTS = [
 {id:'oda',name:'織田木瓜',reading:'おだもっこう',clan:'織田家',person:'織田信長',kind:'植物',line:'幾重もの輪郭の、その奥へ。',prompt:'花にも、窓にも見える。この向こうに、どんな部屋があるだろう。',note:'織田家の紋として知られる木瓜紋。五つに分かれた外形と内側の細かな形が重なります。',source:'https://www.city.gifu.lg.jp/kankoubunka/kankou/1013050/1005149/1017450/1017465/1020522.html',sourceName:'岐阜市｜織田信長の家紋：木瓜',file:'Japanese Crest Oda ka.svg'},
 {id:'takeda',name:'武田菱',reading:'たけだびし',clan:'武田家',person:'武田信玄',kind:'幾何',line:'離れていても、ひとつのかたち。',prompt:'四つのかけらを隔てる、細い余白。そこを通るものは何だろう。',note:'武田氏にゆかりのある菱紋。家紋の起源には諸説があり、信玄の所用品には花菱も見られます。ここでは四つの菱を鑑賞用に作図しています。',source:'https://www.lib.pref.yamanashi.jp/reference/jirei/yamanashi.html',sourceName:'山梨県立図書館｜山梨に関するレファレンス事例'},
 {id:'sanada',name:'六連銭',reading:'ろくれんせん ろくもんせん',clan:'真田家',person:'真田昌幸・信繁',kind:'幾何',line:'六つの円に、六つの余白。',prompt:'これは窓だろうか、切符だろうか。六つだけ持って旅に出るなら。',note:'六文銭とも呼ばれる、真田家にゆかりの紋。丸い銭と四角い穴の対比を眺めます。配置と線幅は鑑賞用の作図です。',source:'https://www.city.ueda.nagano.jp/soshiki/shoko/11716.html',sourceName:'上田市｜真田氏ゆかりの意匠'},
 {id:'hojo',name:'三つ鱗',reading:'みつうろこ',clan:'北条家',person:'北条氏康',kind:'幾何',line:'三角が、もう一つの三角になる。',prompt:'真ん中の空白にも、かたちがある。そこには何を置きたいだろう。',note:'小田原の北条氏にゆかりの鱗紋。三つの三角と、その間の余白から成ります。鱗紋には角度や比率の異なる図案があります。',source:'https://www.city.odawara.kanagawa.jp/global-image/Press/20210372-1.pdf',sourceName:'小田原市｜小田原城御城印の意匠（PDF）'},
 {id:'shimazu',name:'丸に十の字',reading:'まるにじゅうのじ',clan:'島津家',person:'島津義弘',kind:'幾何',line:'円の内側に、四つの景色。',prompt:'四つに分かれた窓。朝、昼、夕、夜。それぞれに何が見えるだろう。',note:'島津家にゆかりの丸に十の字。鹿児島市章の基にもなった意匠です。輪と直線の関係を鑑賞用に作図しています。',source:'https://www.city.kagoshima.lg.jp/gikai/seimuchousa/shigikai/koho/shisegaiyo/documents/r400tobiramokuji.pdf',sourceName:'鹿児島市｜市章について（PDF）'},
 {id:'mori',name:'一文字三星',reading:'いちもんじみつぼし',clan:'毛利家',person:'毛利元就',kind:'幾何',line:'一本の線と、その下の星。',prompt:'水平線の下に星がある。上下の入れ替わった世界を、少しだけ想像する。',note:'毛利家に伝わる一文字と三つの星の紋。一文字の表現などに異同があります。ここでは直線と三つの円で作図しています。',source:'https://www.city.hofu.yamaguchi.jp/uploaded/attachment/73654.pdf',sourceName:'防府市｜毛利家の家紋（PDF）'},
 {id:'hosokawa',name:'九曜',reading:'くよう',clan:'細川家',person:'細川忠興',kind:'幾何',line:'ひとつを囲む、小さな宇宙。',prompt:'真ん中にひとつ、まわりに八つ。この集まりに名前をつけるなら。',note:'細川家では忠興の時代から用いられた九曜紋。天体に関わる意匠です。円の大きさや間隔は時代によって異なり、本作は鑑賞用の配置です。',source:'https://www.let.kumamoto-u.ac.jp/eisei/about/faq.html',sourceName:'熊本大学永青文庫研究センター｜九曜紋について'},
 {id:'kato',name:'蛇の目',reading:'じゃのめ',clan:'加藤家',person:'加藤清正',kind:'幾何',line:'何もない中心に、目がとまる。',prompt:'丸い穴から、ひとつだけ見えるとしたら。いま、何を見てみたいだろう。',note:'加藤家の紋として伝わる蛇の目。八代市立博物館の所蔵品にも見られます。円環の太さは鑑賞用に整えています。',source:'https://www.city.yatsushiro.kumamoto.jp/museum/search/dtl.jsp?cgid=83&kid=94583&searchstr=',sourceName:'八代市立博物館｜蛇目紋陣羽織'},
 {id:'kuroda',name:'白餅',reading:'しろもち',clan:'黒田家',person:'黒田孝高・長政',kind:'幾何',line:'ただ、まるい。それだけの強さ。',prompt:'月、石、餅、遠くの灯り。この円は、いま何に見えるだろう。',note:'黒田家の表紋とされた白餅。藤巴とともに伝わる家紋です。単純な円が、見る背景によって違う印象を生みます。',source:'https://museum.city.fukuoka.jp/archives/leaflet/428/index.html',sourceName:'福岡市博物館｜藤と餅―黒田家家紋ものがたり―'},
 {id:'maeda',name:'加賀梅鉢',reading:'かがうめばち けんうめばち',clan:'前田家',person:'前田利家',kind:'植物',line:'まるい花に、鋭い気配。',prompt:'やわらかなものの間に、尖ったものがある。そんな風景を覚えているだろうか。',note:'加賀前田家の梅鉢紋は剣梅鉢とも呼ばれます。前田家でも分家によって梅鉢の意匠が異なります。',source:'https://www.ishibi.pref.ishikawa.jp/collection/index.php?app=yougo&data_id=21',sourceName:'石川県立美術館｜梅鉢紋',file:'Japanese crest Kaga Umebachi.svg'},
 {id:'akechi',name:'桔梗',reading:'ききょう',clan:'明智家',person:'明智光秀',kind:'植物',line:'五枚の花びらが、静かにひらく。',prompt:'ひらく直前の花と、ひらいた後の花。今日はどちらの気分だろう。',note:'明智光秀ゆかりの桔梗紋。亀岡市の光秀肖像の解説でも、着物の桔梗紋が紹介されています。桔梗紋の細部には複数の図案があります。',source:'https://museums.city.kameoka.kyoto.jp/database/47ca27-94/',sourceName:'亀岡市文化資料館｜明智光秀像',file:'Japanese crest Kikyou.svg'},
 {id:'tokugawa',name:'三つ葉葵',reading:'みつばあおい',clan:'徳川家',person:'徳川家康',kind:'植物',line:'葉脈に、細い道を見つける。',prompt:'三枚の葉が寄り添うところ。その小さな中心から、どんな道が続くのだろう。',note:'徳川家ゆかりの葵紋。掲載図案は旧意匠として公開されている作図を使用しています。時代・家系・品物による違いがあり、特定の所用品の復元ではありません。',source:'https://www.tokugawa-art-museum.jp/exhibits/planned/items/150801_list.pdf',sourceName:'徳川美術館｜家康の遺産 展示目録（PDF）',file:'Japanese crest Tokugawa Aoi (old design).svg'},
 {"id": "date", "name": "竹に雀", "reading": "たけにすずめ せんだいざさ", "clan": "伊達家", "person": "伊達政宗", "kind": "鳥と蝶", "line": "竹の輪の中で、ふたりの話。", "prompt": "向かい合う二羽は、何を話しているのだろう。葉の音にまぎれた会話を想像する。", "note": "伊達家に伝わる竹に雀。仙台市博物館の所蔵する服飾にも見られます。本作では仙台笹として公開された図案を使用し、上杉笹との違いも眺められます。", "source": "https://www.city.sendai.jp/museum/shuzohin/shuzohin/shuzohin-07.html", "sourceName": "仙台市博物館｜主な収蔵品・服飾", "file": "Take ni Suzume.svg", "author": "Ash_Crow", "license": "Public domain"},
 {"id": "uesugi", "name": "上杉笹", "reading": "うえすぎざさ たけにすずめ", "clan": "上杉家", "person": "上杉謙信", "kind": "鳥と蝶", "line": "同じ鳥にも、違う居場所。", "prompt": "葉の数や向きが変わると、鳥たちの会話まで変わって聞こえるだろうか。", "note": "竹に雀は上杉家にもゆかりのある紋。本作では九枚の笹と向かい合う雀を描いた上杉笹の図案を使用しています。上杉家の中でも米沢笹などの異同があります。", "source": "https://mogamiyoshiaki.jp/?l=46388&p=log", "sourceName": "最上義光歴史館｜竹に雀の家紋", "file": "Japanese Crest Uesugi Sasa.svg"},
 {"id": "ikeda", "name": "揚羽蝶", "reading": "あげはちょう", "clan": "池田家", "person": "池田輝政", "kind": "鳥と蝶", "line": "飛び立つ前の、静かな羽。", "prompt": "この蝶が一度だけ羽ばたいたら、どんな景色が現れるだろう。", "note": "池田家にゆかりの揚羽蝶。岡山城の出土瓦にも蝶の意匠が見られます。揚羽蝶には輪郭や細部の異なる図案があり、本作はその一例です。", "source": "https://www.city.okayama.jp/kurashi/cmsfiles/contents/0000005/5127/000060535.pdf", "sourceName": "岡山市｜岡山城跡の出土遺物（PDF）", "file": "Ageha-cho.svg", "author": "Júlio Reis & Misogi"},
 {"id": "nanbu", "name": "南部鶴", "reading": "なんぶつる むかいづる", "clan": "南部家", "person": "南部信直", "kind": "鳥と蝶", "line": "羽の内側に、星を抱いて。", "prompt": "向かい合った羽が、ひとつの輪になる。ふたりでつくれる場所を思い浮かべる。", "note": "向かい合う二羽の鶴と、胸元の九曜が特徴の南部鶴。青森県の文化財解説でも、この特徴をもつ漆器が紹介されています。", "source": "https://www.pref.aomori.lg.jp/soshiki/kyoiku/e-bunka/juho_kougei_29.html", "sourceName": "青森県｜南部鶴紋蒔絵漆器", "file": "Japanese Crest Nanbu Turu.svg"},
 {"id": "ii", "name": "彦根橘", "reading": "ひこねたちばな いいたちばな", "clan": "井伊家", "person": "井伊直政", "kind": "植物", "line": "小さな実に、ゆたかな輪郭。", "prompt": "葉の上にのったひとつの実。大切なものを、こんなふうに包むとしたら。", "note": "井伊家にゆかりの橘紋。彦根城博物館では橘を意匠にした鞍と鐙も紹介されています。本作では彦根橘・井伊橘と呼ばれる図案を使用しています。", "source": "https://hikone-castle-museum.jp/collection/254.html", "sourceName": "彦根城博物館｜金梨地枝橘文蒔絵鞍・同鐙", "file": "Japanese crest Hikone Tachibana.svg"},
 {"id": "toyotomi", "name": "五七桐", "reading": "ごしちのきり ごしちぎり", "clan": "豊臣家", "person": "豊臣秀吉", "kind": "植物", "line": "三枚の葉から、空へ伸びる。", "prompt": "上へ伸びる花と、横へ広がる葉。いまの思いは、どちらに近いだろう。", "note": "豊臣家にゆかりの桐紋の一つ。五七桐は中央に七、左右に五の花を配する図案です。桐紋は豊臣家だけに限らず用いられ、細部にも違いがあります。", "source": "https://osakacastle.net/library/collection/24/", "sourceName": "大阪城天守閣｜伝 豊臣秀吉所用の桐文軍配", "file": "Goshichi no kiri.svg", "author": "Zagyoso", "license": "Public domain"},
 {"id": "chosokabe", "name": "丸に七つ片喰", "reading": "まるにななつかたばみ", "clan": "長宗我部家", "person": "長宗我部元親", "kind": "植物", "line": "七つの葉が、輪の中で出会う。", "prompt": "似たかたちを集めたら、一枚では見えなかった何かが生まれる。何を集めてみたいだろう。", "note": "長宗我部家にゆかりの七つ片喰。カタバミの葉を組み合わせる紋で、本作は丸で囲った図案を掲載しています。", "source": "https://www.meihaku.jp/family-crest-illust/", "sourceName": "名古屋刀剣博物館｜武将の家紋一覧", "file": "Nanatsukatabami.svg", "author": "百楽兎"},
 {"id": "shibata", "name": "二つ雁金", "reading": "ふたつかりがね にかりがね", "clan": "柴田家", "person": "柴田勝家", "kind": "鳥と蝶", "line": "同じ空を、少しずれて飛ぶ。", "prompt": "先を行く鳥と、あとを追う鳥。その間には、どんな言葉が行き来するだろう。", "note": "柴田勝家にゆかりの二つ雁金。本作では上の鳥がくちばしを開いた柴田氏の図案を使用しています。丸で囲うものなどの違いもあります。", "source": "https://www.city.gifu.lg.jp/kankoubunka/kankou/1013050/1005149/1017450/1017465/1020524.html", "sourceName": "岐阜市｜柴田勝家の家紋：雁金", "file": "Japanese Crest futatu Karigane.svg"},
 {"id": "todo", "name": "蔦", "reading": "つた とうどうづた", "clan": "藤堂家", "person": "藤堂高虎", "kind": "植物", "line": "ひとつの葉に、道が分かれる。", "prompt": "葉脈を地図のようにたどる。この道の先に、小さな家を建てるなら。", "note": "藤堂家にゆかりの蔦紋。藤堂家伝来の具足にも蔦が見られます。本作は蔦の基本図案を掲載しています。藤堂蔦など、葉の輪郭・比率・葉脈には異同があります。", "source": "https://www.fujibi.or.jp/collection/artwork/00730/", "sourceName": "東京富士美術館｜藤堂家伝来の具足", "file": "Japanese crest Tuta.svg"},
 {"id": "nabeshima", "name": "鍋島杏葉", "reading": "なべしまぎょうよう", "clan": "鍋島家", "person": "鍋島直茂", "kind": "道具", "line": "葉のような、飾りのような。", "prompt": "左右のかたちが、そっと何かを包んでいる。真ん中に置くなら、どんな記憶だろう。", "note": "鍋島家の杏葉紋。杏葉は馬具の装飾に由来する意匠です。鍋島家では花杏葉や筋杏葉などが使われました。掲載図案は筋を描いた鍋島杏葉で、直茂本人の所用品の復元ではありません。", "source": "https://www.nabeshima.or.jp/collection/index.php?id=154&mode=display_itemdetail", "sourceName": "徴古館｜鍋島本家の筋杏葉紋", "file": "Japanese Crest Nabesima Gyouyou.svg"},
 {"id": "mizuno", "name": "水野沢瀉", "reading": "みずのおもだか", "clan": "水野家", "person": "水野勝成", "kind": "植物", "line": "水面から、まっすぐ伸びる。", "prompt": "二本の波の上に立つ葉。風のない朝、この水辺にはどんな音がするだろう。", "note": "水野家にゆかりの沢瀉紋。掲載図案では植物の下に二本の波線が添えられています。水野家でも系統や使う品によって図案は異なります。", "source": "https://www.city.yuki.lg.jp/kosodate-kyouiku/shougaigakushuu/column/page008595.html", "sourceName": "結城市｜水野家物語", "file": "Japanese Crest Mizuno Omodaka.svg"},
 {"id": "tachibana", "name": "立花守", "reading": "たちばなまもり やながわまもり ぎおんまもり", "clan": "立花家", "person": "立花宗茂", "kind": "道具", "line": "結び目に、思いをしまう。", "prompt": "結んだものと、ほどいたもの。今日はどちらを、手のひらに残しておきたいだろう。", "note": "立花家に伝わる祇園守紋の一種で、柳川守とも呼ばれます。本作は江戸中期ごろの図案として公開されたものです。初期は比較的縦長で、宗茂の時代の現物を復元したものではありません。", "source": "https://www.city.yanagawa.fukuoka.jp/library/download/shisei/13100102.pdf", "sourceName": "柳川市｜柳川の御花・立花家史料館（PDF）", "file": "Japanese Crest Tachibana Mamori.svg"},
 {"id": "satake", "name": "日の丸扇", "reading": "ひのまるおうぎ ごほんぼねおうぎ つきまる", "clan": "佐竹家", "person": "佐竹義重・義宣", "kind": "道具", "line": "ひらけば、風の居場所になる。", "prompt": "扇の中に浮かぶ丸を、遠くの景色に見立てる。そこから、どんな風が届くだろう。", "note": "佐竹家にゆかりの、五本骨と丸を配した扇紋。秋田県公文書館の系図目録には「五本骨扇之内日ノ丸」として記録されています。扇の丸を月として呼ぶものもあり、名称や細部には異同があります。", "source": "https://www.pref.akita.lg.jp/uploads/public/archive_0000000413_00/004keizumokuroku1.pdf", "sourceName": "秋田県公文書館｜系図目録Ⅰ・佐竹家の紋（PDF）", "file": "Japanese Crest Hinomaru Oogi.svg"},
 {"id": "honda", "name": "本多立ち葵", "reading": "ほんだたちあおい", "clan": "本多家", "person": "本多忠勝", "kind": "植物", "line": "葉は、上を向いている。", "prompt": "同じ葵でも、立ち上がると景色が変わる。横になっていた思いを、起こしてみる。", "note": "三河本多氏にゆかりの立ち葵紋。徳川家の三つ葉葵とは異なり、茎と葉の立ち姿を描きます。本多家の甲冑に配された立葵も、岡崎市の博物館資料で紹介されています。", "source": "https://www.city.okazaki.lg.jp/museum/publication/p021496_d/fil/vol27.pdf", "sourceName": "岡崎市美術博物館｜アルカディア双書27（PDF）", "file": "Japanese crest Honda Tachi Aoi.svg", "license": "Public domain"},
 {"id": "sakai", "name": "姫路剣片喰", "reading": "ひめじけんかたばみ", "clan": "酒井家", "person": "酒井正親・重忠", "kind": "植物", "line": "やわらかい葉に、三つの切先。", "prompt": "丸みと鋭さが、ひとつのかたちに同居する。あなたなら、何と何を組み合わせるだろう。", "note": "酒井家に伝わる剣片喰。本作は姫路剣片喰の図案です。姫路の酒井家による使用は江戸時代の資料にも見られます。酒井家には複数の系統と紋があり、武将本人の現物の復元ではありません。", "source": "https://www.city.ishioka.lg.jp/data/doc/1620260191_doc_191_1.pdf", "sourceName": "石岡市｜姫路城・近世の瓦（PDF）", "file": "Japanese Crest Himeji ken katabami.svg"},
 {"id": "kyogoku", "name": "平四つ目結", "reading": "ひらよつめゆい", "clan": "京極家", "person": "京極高次", "kind": "幾何", "line": "四つの窓から、四つの予感。", "prompt": "隣り合う四つの窓に、違う季節が見えるとしたら。最初にどこをのぞくだろう。", "note": "京極家にゆかりの目結紋。丸亀の京極本家では平四つ目結が用いられました。豊岡の分家などでは向きの違う紋もあり、本作は基本形を鑑賞用に作図しています。", "source": "https://www3.city.toyooka.lg.jp/kokubunjikan/kanpou/kanpou2019.pdf", "sourceName": "豊岡市立歴史博物館｜館報・京極家の紋（PDF）"},
 {"id": "niwa", "name": "直違", "reading": "すじかい ちがいぼう にわすじかい", "clan": "丹羽家", "person": "丹羽長秀", "kind": "幾何", "line": "二本の線が、そこで出会う。", "prompt": "交わる前と、交わった後。同じ二本でも、何が変わったのだろう。", "note": "丹羽家の直違紋は違い棒とも呼ばれます。細長い二本の形を交差させた意匠です。本作は角度や線幅を鑑賞用に整えて作図しています。", "source": "https://www.city.nihonmatsu.lg.jp/file/webook/151/pageindices/index2.html", "sourceName": "二本松市｜広報にほんまつ・丹羽家の直違紋"},
 {"id": "ashikaga", "name": "丸に二つ引両", "reading": "まるにふたつひきりょう ふたっぴき", "clan": "足利家", "person": "足利義輝・義昭", "kind": "幾何", "line": "二本の水平線を、丸く包む。", "prompt": "二つの水平線のあいだは、海だろうか、空だろうか。何も描かれていない場所を眺める。", "note": "足利氏にゆかりの二引紋。円の中に二本の横線を配します。栃木県立博物館でも丸に二つ引両として紹介されています。本作は基本形の鑑賞用作図です。", "source": "https://www.muse.pref.tochigi.lg.jp/news/2012/11/post-160.html", "sourceName": "栃木県立博物館｜足利氏の二引紋"}
];
export const PALETTES = [
 {name:'銀と墨',paper:'#151513',ink:'#c9c6bd'},
 {name:'墨と生成り',paper:'#e8e0d0',ink:'#31332f'},
 {name:'藍の夜',paper:'#192c3b',ink:'#d9ded9'},
 {name:'苔の庭',paper:'#303c34',ink:'#d7d7bd'},
 {name:'紅の余韻',paper:'#542f36',ink:'#e9d6c4'}
];
export function todayIndex(date = new Date()) {
 const day = new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Tokyo',year:'numeric',month:'2-digit',day:'2-digit'}).format(date);
 return [...day].reduce((n,c)=>(n*31+c.charCodeAt(0))>>>0,0)%CRESTS.length;
}
export function nextRandom(index, random = Math.random) { return (index+1+Math.floor(random()*(CRESTS.length-1)))%CRESTS.length; }

export function artCredit(crest) {
 return {author: crest.author || (crest.file ? "Mukai" : "HiNa Kihi"), license: crest.license || (crest.file ? "CC BY-SA 3.0" : "CC0 1.0"), url: crest.file ? "https://commons.wikimedia.org/wiki/File:" + encodeURIComponent(crest.file) : "", licenseURL: crest.license === "Public domain" ? "https://en.wikipedia.org/wiki/Public_domain" : crest.file ? "https://creativecommons.org/licenses/by-sa/3.0/" : "https://creativecommons.org/publicdomain/zero/1.0/"};
}
