const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export const reflectionTitles=['場面を確かめる','判断のつながりを見る','考え方に言い換える','自分への問いにする','関連する言葉を読む'];
function anchor(c,b,diagram){return `<aside class="reflection-anchor"><p class="meta">この考えの出発点</p><h3>${esc(c.subtitle)}</h3><div class="anchor-figure">${diagram(c,b.mapStep)}</div><p class="anchor-look">${esc(b.look)}</p><p class="disclaimer">● ${esc(c.sides[0])}${['baggage','mulberry'].includes(c.id)?'':' ／ ◆ '+esc(c.sides[1])}<br>実線：${c.kind==='theory'?'説明上の経路':'行動'} ／ 破線：計画・見立て<br>位置・縮尺を再現しない${c.kind==='theory'?'概念':'概略'}図</p><div class="anchor-actions"><button type="button" data-reflection-zoom>図を大きく見る ＋</button><button type="button" data-return-map>布陣の「${['状況','判断','展開','結果'][b.mapStep]}」に戻る ↗</button></div></aside>`;}
function terms(b,work=false){return `<div class="mapping-wrap"><table class="mapping"><caption>${work?'歴史のどこを、仕事の何へ置き換えるか':'図の中のものを、関係の言葉へ'}</caption><thead><tr><th scope="col">${work?'歴史で見たこと':'図にあるもの'}</th><th scope="col">関係に言い換える</th>${work?'<th scope="col">仕事での例</th>':''}</tr></thead><tbody>${b.terms.map(row=>`<tr>${row.slice(0,work?3:2).map((t,i)=>i===0?`<th scope="row">${esc(t)}</th>`:`<td>${esc(t)}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;}
export function thoughtView(c,b,index,{diagram,quoteHTML,quotes}){
 let body='';
 if(index===0)body=`<p class="reflection-lead">まず、布陣の「${['状況','判断','展開','結果'][b.mapStep]}」にある一場面を確かめます。</p><div class="scene-recap"><span class="meta">${esc(c.steps[b.mapStep].title)}</span><p>${esc(c.steps[b.mapStep].text)}</p></div><p>この場面の${c.kind==='theory'?'考え':'判断'}を、次で少しほどいてみます。まだ教訓を決めなくて大丈夫です。</p>`;
 if(index===1)body=`<dl class="reason-chain"><div><dt>置かれていた条件</dt><dd>${esc(b.condition)}</dd></div><div><dt>そこで選んだこと</dt><dd>${esc(b.choice)}</dd></div><div><dt>${c.kind==='theory'?'この図の行き着く先':'その後の展開'}</dt><dd>${esc(c.steps[3].text)}</dd></div></dl><p class="disclaimer">資料をもとに関係を整理したものです。当事者の内心を再現したものではありません。</p>`;
 if(index===2)body=`<p class="reflection-lead">${esc(b.connection)}</p>${terms(b)}<div class="picked-thought"><span class="meta">この関係から拾う考え · 本作の編集</span><h3>${esc(c.insight)}</h3></div>`;
 if(index===3)body=`<p class="reflection-lead">${esc(b.selfLead)}</p><ol class="gentle-prompts">${b.prompts.map(t=>`<li>${esc(t)}</li>`).join('')}</ol><div class="picked-thought"><span class="meta">最後に、自分へ一つ</span><p class="question">${esc(c.question)}</p></div><p>答えは決まらなくても大丈夫です。引っかかったところだけ、手もとに残せます。</p><button type="button" data-write-note>この問いから、メモを書く ↓</button>`;
 if(index===4)body=`<p class="reflection-lead">${esc(b.quoteReason)}</p><div class="guided-quote">${quoteHTML(quotes[c.quote])}</div><p class="disclaimer">ここまでの説明と問いは本作の編集です。引用の原文と、そこからの読み取りは分けて眺めてください。</p>`;
 return `<div class="reflection-intro"><p>図から考え方へ、五つの小さな段階で。</p><span class="meta">好きな段階に戻れます。答えの入力は必要ありません。</span></div><nav class="reflection-progress" aria-label="思考を拾う五つの段階">${reflectionTitles.map((title,i)=>`<button type="button" data-reflect-step="${i}" aria-current="${i===index?'step':'false'}"><span>0${i+1}</span>${esc(title)}</button>`).join('')}</nav><div class="reflection-layout">${anchor(c,b,diagram)}<article class="reflection-reading" aria-labelledby="reflection-title"><span class="chapter-count">0${index+1} / 05</span><h2 id="reflection-title" tabindex="-1">${reflectionTitles[index]}</h2>${body}<nav class="reflection-controls" aria-label="思考の前後へ">${index===0?'<button type="button" data-return-map>← 布陣に戻る</button>':`<button type="button" data-reflect-step="${index-1}">← 前の段階へ</button>`}${index===4?'<button class="primary" type="button" data-go-work>この考えを仕事に映す →</button>':`<button class="primary" type="button" data-reflect-step="${index+1}">次へ：${reflectionTitles[index+1]} →</button>`}</nav>${index<4?'<p class="reflection-shortcut"><button type="button" data-go-work>仕事での例を先に見る ↗</button></p>':''}</article></div>`;
}
export function workView(c,b,{diagram,quoteHTML,quotes}){
 return `<div class="reflection-intro"><p>いま見た関係を、身近な仕事へ。</p><span class="meta">置き換えと具体例は本作の編集です。</span></div><div class="reflection-layout">${anchor(c,b,diagram)}<article class="reflection-reading work-reading"><section><span class="chapter-count">01 / つながりを確かめる</span><h2 id="work-title" tabindex="-1">${esc(c.insight)}</h2><p>${esc(b.connection)}</p><button class="quiet-button" type="button" data-go-thought="2">思考を拾うの「言い換え」を読み直す ↗</button>${terms(b,true)}</section><section class="work-example"><span class="chapter-count">02 / 仕事の場面なら</span><h3>${esc(c.business)}</h3><dl class="before-after"><div><dt>たとえば、こんな進め方から</dt><dd>${esc(b.before)}</dd></div><div><dt>今の考えを使うと</dt><dd>${esc(b.after)}</dd></div></dl></section><section class="work-try"><span class="chapter-count">03 / 自分の仕事で、小さく試す</span><h3>${esc(c.action)}</h3><p class="question">${esc(c.question)}</p><button type="button" data-write-note>自分の場合を、書きとめる ↓</button><details class="work-caveat"><summary>歴史と仕事で違うところ</summary><p>${esc(c.limit)}</p></details></section><details class="work-extra"><summary>もう一つの関連する言葉を読む</summary><p class="disclaimer">理解を広げるための別の出典です。この出来事の当事者の言葉とは限りません。</p><div class="guided-quote">${quoteHTML(quotes[c.relatedQuote])}</div></details></article></div>`;
}
